import mathSrc from '../core/math.js?raw';
import hashSrc from '../core/hash.js?raw';
import easeSrc from '../core/ease.js?raw';
import shapesSrc from '../core/shapes.js?raw';
import lrcSrc from '../core/lrc.js?raw';
import renderSrc from '../core/render.js?raw';
import hostBridgeSrc from './hostBridge.template.js?raw';
import { esc } from '../lib/esc';
import type { Project } from '../types/project';

// core/*.js are plain ES modules for normal (bundled) use by the live preview/timeline.
// For export we concatenate their literal source into one flat IIFE — same code path the
// live app runs, no duplicate hand-copy — so `import`/`export` syntax has to come out first.
function stripModuleSyntax(src: string): string {
  return src
    .replace(/^import\s[\s\S]*?;\s*$/gm, '') // handles multi-line `import {\n ... \n} from '...';` too
    .replace(/^export\s+/gm, '')
    .trim();
}

function stripKeyframeIds(project: Project): unknown {
  const stripped = structuredClone(project) as any;
  for (const layer of stripped.layers) {
    for (const key of Object.keys(layer.tracks)) {
      layer.tracks[key] = layer.tracks[key].map(({ id, ...rest }: any) => rest);
    }
  }
  return stripped;
}

export function buildVisualizerHtml(project: Project): string {
  const slug = project.meta.slug || 'track';
  const hasLyrics = project.layers.some((l) => l.type === 'lyrics');

  const coreModules = [mathSrc, hashSrc, easeSrc, shapesSrc, hasLyrics ? lrcSrc : '', renderSrc]
    .filter(Boolean)
    .map(stripModuleSyntax)
    .join('\n\n');

  // Preserves the host's `delta-data-json:<slug>_lrc` substitution contract byte-for-byte
  // (never actually substituted today — an inert placeholder branch). The fallback no longer
  // re-parses a separately embedded raw-LRC string: that duplicated `layer.params.words`
  // (already correct, already carries the keyWords-derived isKey flags) and, worse, always
  // re-derived words with an *empty* key-word set, silently losing key-word highlighting on
  // export whenever a raw LRC had been imported. Falling back straight to the layer's own
  // `params.words` fixes both, and — since it's per-layer — no longer collapses every lyrics
  // layer onto whichever one happened to be first in the array.
  const lyricWordsFn = hasLyrics
    ? [
        'function getLyricWords(layer) {',
        `  var boundLyrics = "delta-data-json:${slug}_lrc";`,
        '  var hostLrcText = (typeof boundLyrics === "string" && boundLyrics.trim() && boundLyrics !== "null" && boundLyrics.indexOf("delta-data-json:") !== 0) ? boundLyrics : null;',
        '  if (hostLrcText) return flattenWords(parseLRC(hostLrcText), {});',
        '  return layer.params.words || [];',
        '}',
      ].join('\n')
    : 'function getLyricWords(layer) { return []; }';

  const driver = [
    '(function(){',
    coreModules,
    '',
    `var PROJECT=${JSON.stringify(stripKeyframeIds(project))};`,
    '',
    lyricWordsFn,
    '',
    hostBridgeSrc.trim(),
    '})();',
  ].join('\n');

  return [
    '<!DOCTYPE html>',
    '<html>',
    '<head>',
    '<meta charset="utf-8">',
    `<title>${esc(project.meta.title)} - Visualizer</title>`,
    '<style>* { margin:0; padding:0; box-sizing:border-box; } html, body { width:100%; height:100%; background:#000; overflow:hidden; }',
    'canvas { position:fixed; top:0; left:0; width:100%; height:100%; display:block; } #cover-img { display:none; }</style>',
    '</head>',
    '<body>',
    '<canvas id="c"></canvas>',
    '<img id="cover-img" src="delta-asset:cover" crossorigin="anonymous">',
    '<script>',
    '// Generated by tools/visualizer-studio — a baked, deterministic keyframe timeline',
    '// (no procedural randomness), matching the window.spectral / delta-asset /',
    '// delta-data-json host contract used by every other capsule visualizer.',
    driver,
    '<' + '/script>',
    '</body>',
    '</html>',
  ].join('\n');
}
