import { esc } from '../lib/esc';
import type { StoryMeta, StoryPage } from '../types/story';

// The custom typewriter page keeps its single-narrator display as-is — the
// per-page `speaker` field flows into the manifest (buildStoryManifestFragment)
// for the capsule spec's synthesized-pager fallback, not into this driver.
export function buildStoryHtml(meta: StoryMeta, pages: StoryPage[]): string {
  const name = meta.name || 'Narrator';
  const portraitKey = meta.portraitKey || 'portrait';
  const charMs = meta.charMs || 22;
  const hue = meta.hue || 225;
  const pagesJs = JSON.stringify(
    pages.map((p) => p.text),
    null,
    2
  );

  return [
    '<!DOCTYPE html><html><head><meta charset="utf-8"><title>' + esc(name) + ' - Story</title><style>',
    '* { margin:0; padding:0; box-sizing:border-box; } html, body { width:100%; height:100%; background:#06040a; overflow:hidden; }',
    'body { font-family:"Segoe UI", system-ui, sans-serif; cursor:pointer; }',
    '#scrim { position:fixed; inset:0; background: radial-gradient(ellipse at 30% 100%, hsla(' + hue + ',60%,60%,0.10), transparent 60%),',
    '  linear-gradient(180deg, rgba(6,4,10,1) 0%, rgba(9,7,15,1) 55%, rgba(4,3,7,1) 100%); }',
    '#portrait { position:fixed; left:2vw; bottom:0; height:88vh; max-width:46vw; object-fit:contain; object-position:bottom;',
    '  filter:drop-shadow(0 0 40px hsla(' + hue + ',70%,70%,0.18)); opacity:0; transform:translateY(14px); transition:opacity 0.8s ease, transform 0.8s ease; }',
    '#portrait.in { opacity:1; transform:translateY(0); }',
    '#box { position:fixed; right:6vw; bottom:6vh; width:min(58vw, 900px); background:rgba(10,8,16,0.72);',
    '  border:1px solid hsla(' + hue + ',60%,70%,0.22); border-radius:14px; padding:22px 28px 20px; box-shadow:0 0 60px rgba(0,0,0,0.5); }',
    '#name { font-size:13px; font-weight:700; letter-spacing:0.14em; color:#fff6dd; margin-bottom:8px; text-transform:uppercase; }',
    '#text { font-size:19px; line-height:1.55; color:#e9e6f2; white-space:pre-line; min-height:4.6em; }',
    '#foot { display:flex; justify-content:space-between; align-items:center; margin-top:14px; }',
    '#continue { font-size:13px; color:hsla(' + hue + ',70%,80%,0.75); opacity:0; animation:blink 1.4s ease-in-out infinite; }',
    '#continue.show { opacity:1; } @keyframes blink { 0%,100% { opacity:0.25; } 50% { opacity:0.9; } }',
    '#pageCount { font-size:11px; color:rgba(233,230,242,0.35); }',
    '#skip { position:fixed; top:4vh; right:4vw; font-size:12px; color:rgba(233,230,242,0.45); padding:8px 14px;',
    '  border:1px solid rgba(233,230,242,0.18); border-radius:999px; }',
    '</style></head><body>',
    '<div id="scrim"></div>',
    '<img id="portrait" src="delta-asset:' + esc(portraitKey) + '" crossorigin="anonymous">',
    '<div id="box"><div id="name">' + esc(name) + '</div><div id="text"></div>',
    '<div id="foot"><span id="continue">&#9662; click to continue</span><span id="pageCount"></span></div></div>',
    '<div id="skip">Skip &rsaquo;</div>',
    '<script>',
    '// Generated by tools/visualizer-studio — uses the documented custom story',
    '// page contract (docs/formats/spectralis-capsule.md "Story Explainer"): full window.spectral',
    '// bridge, spectral.resume() to hand off to normal playback when the story finishes.',
    'var PAGES = ' + pagesJs + ';',
    'var portraitEl=document.getElementById("portrait"), textEl=document.getElementById("text"),',
    '  continueEl=document.getElementById("continue"), pageCountEl=document.getElementById("pageCount"), skipEl=document.getElementById("skip");',
    'var CHAR_MS = ' + charMs + ';',
    'var state = { pageIndex:0, charIndex:0, lastCharMs:0, active:true, started:false };',
    'function tick(now){',
    '  requestAnimationFrame(tick); if(!state.active) return;',
    '  if(!state.started){ state.started=true; state.lastCharMs=now; portraitEl.classList.add("in"); }',
    '  var page = PAGES[state.pageIndex] || "";',
    '  if(state.charIndex < page.length){',
    '    var advance = Math.floor((now - state.lastCharMs) / CHAR_MS);',
    '    if(advance > 0){ state.charIndex = Math.min(page.length, state.charIndex + advance); state.lastCharMs = now; textEl.textContent = page.slice(0, state.charIndex); }',
    '  }',
    '  continueEl.classList.toggle("show", state.charIndex >= page.length);',
    '  pageCountEl.textContent = (state.pageIndex + 1) + " / " + PAGES.length;',
    '}',
    'function advance(){',
    '  if(!state.active) return;',
    '  var page = PAGES[state.pageIndex] || "";',
    '  if(state.charIndex < page.length){ state.charIndex = page.length; textEl.textContent = page; return; }',
    '  state.pageIndex++;',
    '  if(state.pageIndex >= PAGES.length){ finish(); return; }',
    '  state.charIndex = 0; state.lastCharMs = performance.now(); textEl.textContent = ""; continueEl.classList.remove("show");',
    '}',
    'function finish(){',
    '  if(!state.active) return; state.active = false;',
    '  document.body.style.transition = "opacity 0.6s ease"; document.body.style.opacity = "0";',
    '  (function tryResume(){ if(window.spectral && typeof window.spectral.resume === "function"){ window.spectral.resume(); } else { setTimeout(tryResume, 50); } })();',
    '}',
    'document.body.addEventListener("click", advance);',
    'window.addEventListener("keydown", function(e){ if(e.key === " " || e.key === "Enter"){ e.preventDefault(); advance(); } });',
    'skipEl.addEventListener("click", function(e){ e.stopPropagation(); finish(); });',
    'requestAnimationFrame(tick);',
    '<' + '/script></body></html>',
  ].join('\n');
}
